#!/usr/bin/env python3
"""kb.py — the knowledge base behind /lit-review.

Stdlib only. One KB is one directory:

    <kb>/KB.json          topic, research questions, created date
    <kb>/refs.jsonl       one record per work — the source of truth
    <kb>/searches.jsonl   every query run: round, source, query, hits, new
    <kb>/notes/<key>.md   reading notes (template: ../templates/note.md)
    <kb>/pdf/<key>.pdf    archived full text
    <kb>/text/<key>.txt   pdftotext output, used by verify-quotes
    <kb>/rounds/          round-N-plan.md, round-N-summary.md (written by the agent)
    <kb>/INDEX.md         GENERATED by `render` — never edit by hand
    <kb>/refs.bib         GENERATED by `render`

Every network lookup goes to a public scholarly index (OpenAlex, arXiv, Crossref,
Semantic Scholar). Nothing identifying the user is sent.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

UA = "lit-review-kb/1.0 (scholarly literature review tool)"
STATUSES = ("candidate", "screened_out", "included", "read", "excluded")
TIERS = {
    1: "T1 established",
    2: "T2 peer-reviewed",
    3: "T3 credible preprint",
    4: "T4 weak",
    5: "T5 flagged",
}
STOP = set("a an the of on in for to and with without via from by is are towards toward using at as its".split())


# ---------------------------------------------------------------- io helpers
def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(2)


def http_get(url: str, *, accept: str = "application/json", tries: int = 5, binary: bool = False):
    if "api.openalex.org" in url and os.environ.get("OPENALEX_API_KEY"):
        url += ("&" if "?" in url else "?") + "api_key=" + urllib.parse.quote(os.environ["OPENALEX_API_KEY"])
    headers = {"User-Agent": UA, "Accept": accept}
    if "semanticscholar" in url and os.environ.get("S2_API_KEY"):
        headers["x-api-key"] = os.environ["S2_API_KEY"]
    delay = 2.0
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=40) as r:
                data = r.read()
                return data if binary else data.decode("utf-8", "replace")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None
            if e.code in (429, 500, 502, 503, 504) and attempt < tries - 1:
                ra = e.headers.get("Retry-After") if e.headers else None
                wait = min(float(ra), 65.0) if ra and ra.isdigit() else delay
                print(f"  … HTTP {e.code}, retrying in {wait:.0f}s", file=sys.stderr)
                time.sleep(wait)
                delay *= 2
                continue
            print(f"  ! HTTP {e.code} for {url}", file=sys.stderr)
            return None
        except (urllib.error.URLError, TimeoutError) as e:
            if attempt < tries - 1:
                time.sleep(delay)
                delay *= 2
                continue
            print(f"  ! {e} for {url}", file=sys.stderr)
            return None
    return None


def get_json(url: str):
    txt = http_get(url)
    if not txt:
        return None
    try:
        return json.loads(txt)
    except json.JSONDecodeError:
        return None


class KB:
    def __init__(self, root: str):
        self.root = Path(root).expanduser().resolve()
        self.refs_path = self.root / "refs.jsonl"
        self.search_path = self.root / "searches.jsonl"
        self.meta_path = self.root / "KB.json"

    def require(self) -> "KB":
        if not self.meta_path.exists():
            die(f"{self.root} is not a KB (no KB.json) — run `kb.py init` first")
        return self

    @property
    def meta(self) -> dict:
        return json.loads(self.meta_path.read_text())

    def load(self) -> list[dict]:
        if not self.refs_path.exists():
            return []
        return [json.loads(l) for l in self.refs_path.read_text().splitlines() if l.strip()]

    def save(self, refs: list[dict]) -> None:
        refs = sorted(refs, key=lambda r: r["key"])
        tmp = self.refs_path.with_suffix(".tmp")
        tmp.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in refs))
        tmp.replace(self.refs_path)

    def log_search(self, entry: dict) -> None:
        with self.search_path.open("a") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    def searches(self) -> list[dict]:
        if not self.search_path.exists():
            return []
        return [json.loads(l) for l in self.search_path.read_text().splitlines() if l.strip()]


# ---------------------------------------------------------------- normalisers
def norm_title(t: str) -> str:
    t = unicodedata.normalize("NFKD", t or "").encode("ascii", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9]+", " ", t).strip()


def norm_doi(d: str | None) -> str | None:
    if not d:
        return None
    d = d.strip().lower()
    d = re.sub(r"^https?://(dx\.)?doi\.org/", "", d)
    return d or None


def norm_arxiv(a: str | None) -> str | None:
    if not a:
        return None
    a = a.strip()
    a = re.sub(r"^(arxiv:|https?://arxiv\.org/(abs|pdf)/)", "", a, flags=re.I)
    a = re.sub(r"\.pdf$", "", a)
    a = re.sub(r"v\d+$", "", a)
    return a or None


def arxiv_from_doi(doi: str | None) -> str | None:
    m = re.match(r"10\.48550/arxiv\.(.+)$", doi or "", re.I)
    return m.group(1) if m else None


def surname(name: str) -> str:
    parts = [p for p in re.split(r"[\s,]+", name or "") if p]
    if not parts:
        return ""
    return parts[0] if "," in name else parts[-1]


def make_key(rec: dict, taken: set[str]) -> str:
    last = surname(rec["authors"][0]) if rec.get("authors") else "anon"
    last = norm_title(last).replace(" ", "") or "anon"
    words = [w for w in norm_title(rec.get("title", "")).split() if w not in STOP]
    word = words[0] if words else "untitled"
    base = f"{last}{rec.get('year') or 'nd'}{word}"
    key, n = base, 1
    while key in taken:
        n += 1
        key = f"{base}{chr(ord('a') + n - 2)}" if n <= 27 else f"{base}{n}"
    return key


def find_dup(refs: list[dict], rec: dict) -> dict | None:
    d, a, t = norm_doi(rec.get("doi")), norm_arxiv(rec.get("arxiv")), norm_title(rec.get("title", ""))
    oa = rec.get("openalex")
    for r in refs:
        if d and norm_doi(r.get("doi")) == d:
            return r
        if a and norm_arxiv(r.get("arxiv")) == a:
            return r
        if oa and r.get("openalex") == oa:
            return r
        if t and len(t) > 20 and norm_title(r.get("title", "")) == t:
            return r
    return None


def merge(into: dict, new: dict) -> None:
    """Fill gaps in an existing record; never overwrite a reader's judgement."""
    for k, v in new.items():
        if k in ("found_by",):
            for x in v:
                if x not in into.setdefault("found_by", []):
                    into["found_by"].append(x)
        elif v not in (None, "", [], {}) and into.get(k) in (None, "", [], {}):
            into[k] = v
    # a peer-reviewed version beats a preprint record
    if new.get("venue_type") in ("journal", "conference") and into.get("venue_type") == "preprint":
        into["venue"], into["venue_type"] = new["venue"], new["venue_type"]
        if new.get("doi") and not arxiv_from_doi(new["doi"]):
            into["doi"] = new["doi"]


def blank(**kw) -> dict:
    rec = {
        "key": None, "title": "", "authors": [], "year": None, "venue": "", "venue_type": "unknown",
        "doi": None, "arxiv": None, "openalex": None, "url": None, "pdf_url": None,
        "abstract": "", "cited_by": None, "is_retracted": False, "verified": False,
        "status": "candidate", "relevance": None, "round": 1, "found_by": [],
        "trust": {"prior": None, "tier": None, "factors": {}, "rationale": ""},
        "pdf": None, "text": None, "note": None, "quotes_verified": None,
        "tags": [], "added": dt.date.today().isoformat(),
    }
    rec.update(kw)
    return rec


# ---------------------------------------------------------------- sources
def _oa_abstract(inv: dict | None) -> str:
    if not inv:
        return ""
    pos = sorted((i, w) for w, idx in inv.items() for i in idx)
    return " ".join(w for _, w in pos)


def from_openalex(w: dict) -> dict:
    loc = w.get("primary_location") or {}
    src = loc.get("source") or {}
    doi = norm_doi(w.get("doi"))
    arx = arxiv_from_doi(doi)
    for l in w.get("locations") or []:
        u = (l.get("landing_page_url") or "") + " " + (l.get("pdf_url") or "")
        m = re.search(r"arxiv\.org/(?:abs|pdf)/([\w.\-/]+?)(?:v\d+)?(?:\.pdf)?(?:\s|$)", u)
        if m:
            arx = arx or m.group(1)
    stype = src.get("type")
    wtype = w.get("type")
    if wtype == "preprint" or stype == "repository":
        vt = "preprint"
    elif stype == "journal":
        vt = "journal"
    elif stype == "conference":
        vt = "conference"
    elif wtype in ("book", "book-chapter"):
        vt = "book"
    elif wtype == "dissertation":
        vt = "thesis"
    else:
        vt = "unknown"
    best = w.get("best_oa_location") or {}
    return blank(
        title=w.get("title") or w.get("display_name") or "",
        authors=[a["author"]["display_name"] for a in w.get("authorships", []) if a.get("author")],
        year=w.get("publication_year"),
        venue=src.get("display_name") or "",
        venue_type=vt,
        doi=doi if not arx or not doi or not doi.startswith("10.48550") else doi,
        arxiv=arx,
        openalex=(w.get("id") or "").rsplit("/", 1)[-1] or None,
        url=loc.get("landing_page_url") or w.get("doi"),
        pdf_url=best.get("pdf_url") or (f"https://arxiv.org/pdf/{arx}" if arx else None),
        abstract=_oa_abstract(w.get("abstract_inverted_index")),
        cited_by=w.get("cited_by_count"),
        is_retracted=bool(w.get("is_retracted")),
        verified=True,
    )


def search_openalex(q: str, limit: int, since: int | None, fulltext: bool = False) -> list[dict]:
    """Title+abstract by default: OpenAlex's bare `search=` also matches full text,
    which floods results with papers that merely mention the phrase."""
    params = {"per-page": str(min(limit, 200))}
    filt = []
    if fulltext:
        params["search"] = q
    else:
        filt.append("title_and_abstract.search:" + q.replace(",", " "))
    if since:
        filt.append(f"from_publication_date:{since}-01-01")
    if filt:
        params["filter"] = ",".join(filt)
    if os.environ.get("OPENALEX_MAILTO"):
        params["mailto"] = os.environ["OPENALEX_MAILTO"]
    data = get_json("https://api.openalex.org/works?" + urllib.parse.urlencode(params))
    return [from_openalex(w) for w in (data or {}).get("results", [])]


ATOM = {"a": "http://www.w3.org/2005/Atom", "ax": "http://arxiv.org/schemas/atom"}


def _arxiv_entries(xml: str) -> list[dict]:
    out = []
    root = ET.fromstring(xml)
    for e in root.findall("a:entry", ATOM):
        idurl = e.findtext("a:id", "", ATOM)
        if "/abs/" not in idurl:
            continue
        aid = norm_arxiv(idurl.split("/abs/")[-1])
        jref = e.findtext("ax:journal_ref", "", ATOM).strip()
        doi = e.findtext("ax:doi", None, ATOM)
        out.append(blank(
            title=re.sub(r"\s+", " ", e.findtext("a:title", "", ATOM)).strip(),
            authors=[a.findtext("a:name", "", ATOM) for a in e.findall("a:author", ATOM)],
            year=int(e.findtext("a:published", "0000", ATOM)[:4]) or None,
            venue=jref or "arXiv",
            venue_type="unknown" if jref else "preprint",
            doi=norm_doi(doi),
            arxiv=aid,
            url=f"https://arxiv.org/abs/{aid}",
            pdf_url=f"https://arxiv.org/pdf/{aid}",
            abstract=re.sub(r"\s+", " ", e.findtext("a:summary", "", ATOM)).strip(),
            verified=True,
        ))
    return out


def search_arxiv(q: str, limit: int, since: int | None, fulltext: bool = False) -> list[dict]:
    terms = " AND ".join(f'all:"{t}"' if " " in t else f"all:{t}" for t in _split_query(q))
    url = "https://export.arxiv.org/api/query?" + urllib.parse.urlencode(
        {"search_query": terms, "max_results": str(limit), "sortBy": "relevance"})
    xml = http_get(url, accept="application/atom+xml")
    recs = _arxiv_entries(xml) if xml else []
    time.sleep(3)  # arXiv asks for >=3 s between calls
    return [r for r in recs if not since or (r["year"] or 0) >= since]


def _split_query(q: str) -> list[str]:
    """`"masked diffusion" theorem proving` -> ['masked diffusion', 'theorem', 'proving']"""
    return [a or b for a, b in re.findall(r'"([^"]+)"|(\S+)', q)]


def arxiv_by_title(title: str) -> str | None:
    """Many conference papers have an arXiv twin the DOI record does not link."""
    words = [w for w in norm_title(title).split() if len(w) > 3 and w not in STOP][:6]
    if not words:
        return None
    url = "https://export.arxiv.org/api/query?" + urllib.parse.urlencode(
        {"search_query": " AND ".join(f"ti:{w}" for w in words), "max_results": "5"})
    xml = http_get(url, accept="application/atom+xml")
    time.sleep(3)
    for r in _arxiv_entries(xml) if xml else []:
        if norm_title(r["title"]) == norm_title(title):
            return r["arxiv"]
    return None


def search_s2(q: str, limit: int, since: int | None, fulltext: bool = False) -> list[dict]:
    fields = "title,authors,year,venue,publicationTypes,externalIds,citationCount,abstract,openAccessPdf"
    params = {"query": q, "limit": str(min(limit, 100)), "fields": fields}
    if since:
        params["year"] = f"{since}-"
    data = get_json("https://api.semanticscholar.org/graph/v1/paper/search?" + urllib.parse.urlencode(params))
    out = []
    for p in (data or {}).get("data", []):
        ext = p.get("externalIds") or {}
        types = p.get("publicationTypes") or []
        vt = "journal" if "JournalArticle" in types else "conference" if "Conference" in types else (
            "preprint" if not p.get("venue") or p.get("venue", "").lower().startswith("arxiv") else "unknown")
        out.append(blank(
            title=p.get("title") or "", authors=[a["name"] for a in p.get("authors") or []],
            year=p.get("year"), venue=p.get("venue") or "", venue_type=vt,
            doi=norm_doi(ext.get("DOI")), arxiv=norm_arxiv(ext.get("ArXiv")),
            url=f"https://www.semanticscholar.org/paper/{p.get('paperId')}",
            pdf_url=(p.get("openAccessPdf") or {}).get("url"),
            abstract=p.get("abstract") or "", cited_by=p.get("citationCount"), verified=True,
        ))
    time.sleep(1.5)
    return out


SOURCES = {"openalex": search_openalex, "arxiv": search_arxiv, "s2": search_s2}


def resolve(doi=None, arxiv=None, title=None) -> dict | None:
    """Look an identifier up in a public index. None means it does not resolve —
    which, for a reference someone handed you, is itself a finding."""
    arxiv = norm_arxiv(arxiv)
    doi = norm_doi(doi)
    if arxiv:
        w = get_json(f"https://api.openalex.org/works/doi:10.48550/arXiv.{arxiv}")
        if w and w.get("id"):
            rec = from_openalex(w)
            rec["arxiv"] = arxiv
            # OpenAlex often keeps the arXiv record separate from the published one
            if rec["venue_type"] == "preprint":
                pub = _published_version(rec["title"])
                if pub:
                    merge(rec, pub)
            return rec
        xml = http_get("https://export.arxiv.org/api/query?id_list=" + arxiv, accept="application/atom+xml")
        recs = _arxiv_entries(xml) if xml else []
        return recs[0] if recs else None
    if doi:
        w = get_json(f"https://api.openalex.org/works/doi:{urllib.parse.quote(doi)}")
        if w and w.get("id"):
            return from_openalex(w)
        return from_crossref(doi)
    if title:
        hits = search_openalex(title, 5, None)
        t = norm_title(title)
        for h in hits:
            if norm_title(h["title"]) == t:
                return h
        return None
    return None


def from_crossref(doi: str) -> dict | None:
    c = get_json(f"https://api.crossref.org/works/{urllib.parse.quote(doi)}")
    if not c or not c.get("message"):
        return None
    m = c["message"]
    return blank(
        title=(m.get("title") or [""])[0],
        authors=[f"{a.get('given', '')} {a.get('family', '')}".strip() for a in m.get("author", [])],
        year=((m.get("issued") or {}).get("date-parts") or [[None]])[0][0],
        venue=(m.get("container-title") or [""])[0],
        venue_type={"journal-article": "journal", "proceedings-article": "conference",
                    "posted-content": "preprint", "book-chapter": "book", "monograph": "book",
                    "dissertation": "thesis"}.get(m.get("type"), "unknown"),
        doi=doi, url=m.get("URL"), cited_by=m.get("is-referenced-by-count"), verified=True,
    )


def enrich(rec: dict) -> None:
    """OpenAlex often has no source for proceedings; Crossref usually does."""
    if rec.get("venue_type") == "unknown" and rec.get("doi") and not arxiv_from_doi(rec["doi"]):
        cr = from_crossref(rec["doi"])
        if cr:
            rec["venue"] = rec.get("venue") or cr["venue"]
            rec["venue_type"] = cr["venue_type"]


def _published_version(title: str) -> dict | None:
    t = norm_title(title)
    for h in search_openalex(title, 5, None):
        if norm_title(h["title"]) == t and h["venue_type"] in ("journal", "conference"):
            return h
    return None


def retraction_check(doi: str | None) -> bool | None:
    """Crossref carries Retraction Watch data as `updated-by` notices."""
    if not doi or arxiv_from_doi(doi):
        return None
    c = get_json(f"https://api.crossref.org/works/{urllib.parse.quote(doi)}")
    if not c:
        return None
    m = c.get("message", {})
    for u in m.get("updated-by", []) + m.get("update-to", []):
        if "retract" in (u.get("type", "") + u.get("label", "")).lower():
            return True
    return False


# ---------------------------------------------------------------- trust prior
def trust_prior(r: dict) -> tuple[int, dict]:
    """A *metadata-only* prior. It is a starting point for the reader, never the
    final tier: `set KEY tier=N` after reading is what INDEX.md reports."""
    f = {}
    if r.get("is_retracted"):
        return 5, {"retracted": True}
    if not r.get("verified"):
        return 5, {"unresolved_identifier": True}
    vt = r.get("venue_type")
    f["venue_type"] = vt
    age = max(1, dt.date.today().year - (r.get("year") or dt.date.today().year) + 1)
    cpy = (r.get("cited_by") or 0) / age
    f["citations_per_year"] = round(cpy, 1)
    if vt in ("journal", "conference"):
        tier = 1 if cpy >= 50 and age >= 2 else 2
    elif vt in ("book", "thesis"):
        tier = 2 if cpy >= 5 else 3
    elif vt == "preprint":
        # Never T4 from metadata alone: OpenAlex splits citations between a preprint
        # and its published version, so a low count here is weak evidence of anything.
        tier = 3
        if cpy >= 100:
            f["heavily_cited_preprint"] = True
    else:
        tier = 3
    return tier, f


# ---------------------------------------------------------------- commands
def cmd_init(a):
    kb = KB(a.kb)
    if kb.meta_path.exists() and not a.force:
        die(f"{kb.root} already has a KB — use --force to rewrite KB.json")
    for d in ("notes", "pdf", "text", "rounds"):
        (kb.root / d).mkdir(parents=True, exist_ok=True)
    kb.meta_path.write_text(json.dumps({
        "topic": a.topic, "questions": a.question or [], "created": dt.date.today().isoformat(),
        "inclusion": a.inclusion or "", "exclusion": a.exclusion or "",
    }, indent=2) + "\n")
    kb.refs_path.touch()
    print(f"KB initialised at {kb.root}")


def _ingest(kb: KB, refs: list[dict], recs: list[dict], rnd: int, found_by: str) -> list[dict]:
    new = []
    taken = {r["key"] for r in refs}
    for rec in recs:
        if not rec.get("title"):
            continue
        rec["found_by"] = [found_by]
        dup = find_dup(refs, rec)
        if dup:
            merge(dup, rec)
            continue
        enrich(rec)
        rec["round"] = rnd
        rec["key"] = make_key(rec, taken)
        taken.add(rec["key"])
        rec["trust"]["prior"], rec["trust"]["factors"] = trust_prior(rec)
        refs.append(rec)
        new.append(rec)
    return new


def _row(r: dict, abstract: int = 0) -> str:
    au = (surname(r["authors"][0]) + (" et al." if len(r["authors"]) > 1 else "")) if r["authors"] else "?"
    ids = r.get("arxiv") and f"arXiv:{r['arxiv']}" or r.get("doi") or r.get("openalex") or ""
    s = (f"{r['key']:<28} {r.get('year') or '':<5} T{r['trust'].get('tier') or r['trust'].get('prior') or '?'}"
         f" c={r.get('cited_by') if r.get('cited_by') is not None else '?':<5} {au:<18} {r['title'][:90]}  [{ids}]")
    if abstract and r.get("abstract"):
        s += "\n      " + r["abstract"][:abstract].replace("\n", " ")
    return s


def cmd_search(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    recs = SOURCES[a.source](a.query, a.limit, a.since, a.fulltext)
    new = _ingest(kb, refs, recs, a.round, f"search:{a.source}:{a.query}")
    kb.save(refs)
    kb.log_search({"round": a.round, "source": a.source, "query": a.query, "since": a.since,
                   "hits": len(recs), "new": len(new), "date": dt.date.today().isoformat(),
                   "keys": [r["key"] for r in new]})
    print(f"{a.source} '{a.query}': {len(recs)} hits, {len(new)} new")
    for r in new:
        print("  " + _row(r, a.abstract))


def cmd_add(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    rec = resolve(doi=a.doi, arxiv=a.arxiv, title=a.title)
    if rec is None:
        if not a.title:
            die("identifier does not resolve in OpenAlex/arXiv/Crossref — check it; "
                "pass --title (and --year/--venue) to record it as UNVERIFIED")
        rec = blank(title=a.title, arxiv=norm_arxiv(a.arxiv), doi=norm_doi(a.doi), verified=False)
        print("  ! did not resolve: recorded as unverified (trust prior T5 until checked)")
    for k in ("year", "venue", "url"):
        if getattr(a, k, None):
            rec[k] = getattr(a, k)
    if a.venue_type:
        rec["venue_type"] = a.venue_type
    new = _ingest(kb, refs, [rec], a.round, a.found_by or "manual")
    kb.save(refs)
    if new:
        print("added  " + _row(new[0]))
    else:
        print("already present: " + _row(find_dup(refs, rec)))


def _select(refs, a) -> list[dict]:
    out = refs
    if getattr(a, "keys", None):
        ks = set(a.keys)
        out = [r for r in out if r["key"] in ks]
    if getattr(a, "status", None):
        out = [r for r in out if r["status"] in a.status.split(",")]
    if getattr(a, "round", None):
        out = [r for r in out if r["round"] == a.round]
    if getattr(a, "max_tier", None):
        out = [r for r in out if (r["trust"].get("tier") or r["trust"].get("prior") or 9) <= a.max_tier]
    if getattr(a, "min_relevance", None):
        out = [r for r in out if (r.get("relevance") or 0) >= a.min_relevance]
    return out


def cmd_list(a):
    refs = _select(KB(a.kb).require().load(), a)
    key = {"cited": lambda r: -(r.get("cited_by") or 0), "year": lambda r: -(r.get("year") or 0),
           "key": lambda r: r["key"], "relevance": lambda r: -(r.get("relevance") or 0)}[a.sort]
    for r in sorted(refs, key=key):
        rel = r.get("relevance")
        print(f"[{r['status'][:4]} R{r['round']} rel={rel if rel is not None else '-'}] " + _row(r, a.abstract))
    print(f"{len(refs)} records")


def cmd_show(a):
    refs = {r["key"]: r for r in KB(a.kb).require().load()}
    for k in a.keys:
        print(json.dumps(refs.get(k) or {"missing": k}, indent=2, ensure_ascii=False))


def cmd_set(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    by = {r["key"]: r for r in refs}
    targets = [by[k] for k in a.keys if k in by]
    missing = [k for k in a.keys if k not in by]
    if missing:
        die(f"unknown keys: {missing}")
    for assign in a.assign:
        field, _, val = assign.partition("=")
        try:
            v = json.loads(val)
        except json.JSONDecodeError:
            v = val
        for r in targets:
            if field == "status" and v not in STATUSES:
                die(f"status must be one of {STATUSES}")
            if field in ("tier", "rationale"):
                if field == "tier" and v not in TIERS:
                    die("tier must be 1..5")
                r["trust"][field] = v
            elif field.startswith("factor."):
                r["trust"]["factors"][field[7:]] = v
            elif field == "tag":
                r.setdefault("tags", []).append(v)
            else:
                r[field] = v
    kb.save(refs)
    print(f"updated {len(targets)} record(s)")


def cmd_fetch(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    for r in _select(refs, a):
        pdf = kb.root / "pdf" / f"{r['key']}.pdf"
        if not pdf.exists() and not r.get("arxiv"):
            r["arxiv"] = arxiv_by_title(r["title"])
            if r["arxiv"]:
                print(f"  ..   {r['key']}: found arXiv copy {r['arxiv']} by exact title")
        if not pdf.exists():
            urls = [u for u in (f"https://arxiv.org/pdf/{r['arxiv']}" if r.get("arxiv") else None,
                                r.get("pdf_url")) if u]
            for u in urls:
                data = http_get(u, accept="application/pdf", binary=True)
                if data and data[:5] == b"%PDF-":
                    pdf.write_bytes(data)
                    break
                time.sleep(1)
        if pdf.exists():
            txt = kb.root / "text" / f"{r['key']}.txt"
            if not txt.exists():
                subprocess.run(["pdftotext", "-q", str(pdf), str(txt)], check=False)
            r["pdf"] = f"pdf/{pdf.name}"
            r["text"] = f"text/{txt.name}" if txt.exists() else None
            print(f"  ok   {r['key']}  ({pdf.stat().st_size // 1024} KiB)")
        else:
            print(f"  --   {r['key']}  no open-access PDF found — note must name where the text was read")
    kb.save(refs)


def _qnorm(s: str) -> str:
    s = unicodedata.normalize("NFKC", s)
    s = (s.replace("ﬁ", "fi").replace("ﬂ", "fl").replace("’", "'").replace("‘", "'")
         .replace("“", '"').replace("”", '"').replace("–", "-").replace("—", "-").replace("−", "-"))
    s = re.sub(r"-\s*\n\s*", "", s)           # de-hyphenate line breaks
    s = re.sub(r"\[\d+(,\s*\d+)*\]", "", s)    # numeric citation markers
    s = re.sub(r"[\s\-]+", "", s).lower()   # pdftotext drops/keeps hyphens inconsistently
    return s


def _quotes(note: str) -> list[str]:
    """Block quotes under a '## Verified quotes' heading. Adjacent `>` lines join."""
    m = re.search(r"^## Verified quotes\s*$(.*?)(?=^## |\Z)", note, re.M | re.S)
    if not m:
        return []
    out, cur = [], []
    for line in m.group(1).splitlines():
        if line.startswith(">"):
            cur.append(line[1:].strip())
        elif cur:
            out.append(" ".join(cur))
            cur = []
    if cur:
        out.append(" ".join(cur))
    cleaned = []
    for q in out:
        q = re.sub(r"\s*—\s*(p\.|§|sec|page).*$", "", q, flags=re.I)  # trailing locator
        q = q.strip().strip('"').strip("“”").strip()
        if q:
            cleaned.append(q)
    return cleaned


def cmd_verify_quotes(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    bad_total = 0
    for r in _select(refs, a):
        note = kb.root / "notes" / f"{r['key']}.md"
        if not note.exists():
            continue
        r["note"] = f"notes/{note.name}"
        qs = _quotes(note.read_text())
        txt = kb.root / "text" / f"{r['key']}.txt"
        if not qs:
            r["quotes_verified"] = None
            print(f"  --   {r['key']}: no quotes")
            continue
        if not txt.exists():
            r["quotes_verified"] = None
            print(f"  ??   {r['key']}: {len(qs)} quote(s), no text/ to check against — hand-checked only")
            continue
        body = _qnorm(txt.read_text(errors="replace"))
        bad = []
        for q in qs:
            pieces = [p for p in re.split(r"\s*(?:\.\.\.|…|\[\.\.\.\])\s*", q) if p.strip()]
            if not all(_qnorm(p) in body for p in pieces):
                bad.append(q)
        r["quotes_verified"] = not bad
        bad_total += len(bad)
        print(f"  {'ok ' if not bad else 'BAD'}  {r['key']}: {len(qs) - len(bad)}/{len(qs)} quotes found in text")
        for q in bad:
            print(f"         not found: {q[:140]}")
    kb.save(refs)
    if bad_total:
        sys.exit(1)


def _oa_work(ident: str) -> dict | None:
    return get_json(f"https://api.openalex.org/works/{ident}")


def cmd_chain(a):
    """Backward (references) and forward (cited-by) snowballing from the selected
    seeds. Candidates are ranked by how many seeds link to them — a work cited by
    five of your trusted papers matters more than one cited by one."""
    kb = KB(a.kb).require()
    refs = kb.load()
    seeds = _select(refs, a)
    if not seeds:
        die("no seeds match the selection")
    have = {r.get("openalex") for r in refs if r.get("openalex")}
    votes: dict[str, set[str]] = {}
    for s in seeds:
        oid = s.get("openalex")
        if not oid:
            got = resolve(doi=s.get("doi"), arxiv=s.get("arxiv"), title=None if (s.get("doi") or s.get("arxiv")) else s["title"])
            oid = got and got.get("openalex")
            if oid:
                s["openalex"] = oid
        if not oid:
            got = resolve(title=s["title"])
            oid = got and got.get("openalex")
            if oid:
                s["openalex"] = oid
        back, fwd = [], []
        if oid and a.direction in ("both", "backward"):
            w = _oa_work(oid)
            back = [r.rsplit("/", 1)[-1] for r in (w or {}).get("referenced_works", [])]
        if oid and a.direction in ("both", "forward"):
            data = get_json(f"https://api.openalex.org/works?filter=cites:{oid}&per-page=200&sort=cited_by_count:desc")
            fwd = [w["id"].rsplit("/", 1)[-1] for w in (data or {}).get("results", [])]
        # OpenAlex has no reference list for many arXiv-only records; Semantic Scholar often does
        src = "openalex"
        if (not back and a.direction != "forward") or (not fwd and a.direction != "backward"):
            s2b, s2f = _s2_links(s, a.direction)
            if not back and s2b:
                back, src = s2b, "openalex+s2"
            if not fwd and s2f:
                fwd, src = s2f, "openalex+s2"
        if not oid and not back and not fwd:
            print(f"  --   {s['key']}: not found in OpenAlex or Semantic Scholar, skipped")
            continue
        for w in back + fwd:
            votes.setdefault(w, set()).add(s["key"])
        print(f"  seed {s['key']}: {len(back)} refs, {len(fwd)} citing ({src})")
    ranked = sorted(((k, v) for k, v in votes.items() if k not in have), key=lambda kv: -len(kv[1]))
    ranked = [kv for kv in ranked if len(kv[1]) >= a.min_votes][: a.limit]
    recs = []
    for i in range(0, len(ranked), 50):
        chunk = ranked[i:i + 50]
        data = get_json("https://api.openalex.org/works?per-page=50&filter=openalex:" + "|".join(k for k, _ in chunk))
        by = {w["id"].rsplit("/", 1)[-1]: w for w in (data or {}).get("results", [])}
        for k, v in chunk:
            if k in by:
                rec = from_openalex(by[k])
                rec["_votes"] = sorted(v)
                recs.append(rec)
    new = []
    taken = {r["key"] for r in refs}
    for rec in recs:
        voters = rec.pop("_votes")
        rec["found_by"] = [f"chain:{a.direction}:{','.join(voters)}"]
        rec["chain_votes"] = len(voters)
        if find_dup(refs, rec):
            merge(find_dup(refs, rec), rec)
            continue
        enrich(rec)
        rec["round"] = a.to_round
        rec["key"] = make_key(rec, taken)
        taken.add(rec["key"])
        rec["trust"]["prior"], rec["trust"]["factors"] = trust_prior(rec)
        refs.append(rec)
        new.append(rec)
    kb.save(refs)
    kb.log_search({"round": a.to_round, "source": "chain", "query": f"{a.direction} from {len(seeds)} seeds",
                   "hits": len(votes), "new": len(new), "date": dt.date.today().isoformat(),
                   "keys": [r["key"] for r in new]})
    print(f"{len(votes)} linked works, {len(new)} new candidates (min {a.min_votes} seed links)")
    for r in sorted(new, key=lambda r: -r["chain_votes"]):
        print(f"  votes={r['chain_votes']:<2} " + _row(r))


def _s2_links(r: dict, direction: str) -> tuple[list[str], list[str]]:
    """References / citations from Semantic Scholar, mapped to OpenAlex ids."""
    pid = (f"arXiv:{r['arxiv']}" if r.get("arxiv") else f"DOI:{r['doi']}" if r.get("doi") else None)
    if not pid:
        return [], []
    out = []
    for rel, field in (("references", "citedPaper"), ("citations", "citingPaper")):
        if (rel == "references" and direction == "forward") or (rel == "citations" and direction == "backward"):
            out.append([])
            continue
        data = get_json(f"https://api.semanticscholar.org/graph/v1/paper/{urllib.parse.quote(pid)}/{rel}"
                        f"?fields=externalIds&limit=500")
        time.sleep(1.5)
        dois = []
        for item in (data or {}).get("data", []):
            ext = (item.get(field) or {}).get("externalIds") or {}
            if ext.get("DOI"):
                dois.append(norm_doi(ext["DOI"]))
            elif ext.get("ArXiv"):
                dois.append(f"10.48550/arxiv.{norm_arxiv(ext['ArXiv'])}")
        out.append(_oa_ids_for_dois(dois))
    return out[0], out[1]


def _oa_ids_for_dois(dois: list[str]) -> list[str]:
    ids = []
    for i in range(0, len(dois), 50):
        chunk = dois[i:i + 50]
        data = get_json("https://api.openalex.org/works?per-page=50&select=id&filter=doi:" + "|".join(chunk))
        ids += [w["id"].rsplit("/", 1)[-1] for w in (data or {}).get("results", [])]
    return ids


def cmd_prior(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    for r in _select(refs, a):
        if r.get("venue_type") == "preprint" and not a.no_published:
            pub = _published_version(r["title"])
            if pub:
                merge(r, pub)
                print(f"  ..   {r['key']}: published as {r['venue']}")
        if a.retractions and r.get("doi"):
            rc = retraction_check(r["doi"])
            if rc:
                r["is_retracted"] = True
        r["trust"]["prior"], fac = trust_prior(r)
        r["trust"]["factors"].update(fac)
        print(f"  T{r['trust']['prior']}  {r['key']}  {fac}")
    kb.save(refs)


def _section(text: str, name: str) -> list[str]:
    m = re.search(rf"^## {re.escape(name)}\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    if not m:
        return []
    return [l.strip()[2:].strip() for l in m.group(1).splitlines() if l.strip().startswith(("- ", "* "))]


def cmd_keypoints(a):
    """Everything round N+1 is planned from: key points, open questions, leads,
    contradictions — grouped by trust so the plan leans on the solid ones."""
    kb = KB(a.kb).require()
    refs = [r for r in _select(kb.load(), a) if r["status"] == "read"]
    sections = ("Key points", "Contradictions and tensions", "Open questions", "Leads for next round")
    for sec in sections:
        print(f"\n## {sec}")
        for r in sorted(refs, key=lambda r: (r["trust"].get("tier") or 9, r["key"])):
            p = kb.root / "notes" / f"{r['key']}.md"
            if not p.exists():
                continue
            for item in _section(p.read_text(), sec):
                print(f"- [T{r['trust'].get('tier') or '?'} {r['key']}] {item}")
    print(f"\n({len(refs)} read notes from round {a.round or 'all'})")


def _bib(r: dict) -> str:
    kind = {"journal": "article", "conference": "inproceedings", "thesis": "phdthesis",
            "book": "book"}.get(r["venue_type"], "misc")
    fields = {"title": "{" + r["title"] + "}", "author": " and ".join(r["authors"]) or None,
              "year": r.get("year")}
    if kind == "article":
        fields["journal"] = r["venue"]
    elif kind == "inproceedings":
        fields["booktitle"] = r["venue"]
    if r.get("arxiv"):
        fields.update(eprint=r["arxiv"], archivePrefix="arXiv")
    if r.get("doi"):
        fields["doi"] = r["doi"]
    body = ",\n".join(f"  {k} = {{{v}}}" for k, v in fields.items() if v)
    return f"@{kind}{{{r['key']},\n{body}\n}}\n"


def cmd_render(a):
    kb = KB(a.kb).require()
    meta, refs, searches = kb.meta, kb.load(), kb.searches()
    today = dt.date.today().isoformat()
    by_status = {s: [r for r in refs if r["status"] == s] for s in STATUSES}
    read = by_status["read"]
    rounds = sorted({r["round"] for r in refs} | {s["round"] for s in searches})
    L = [f"# Literature review — {meta['topic']}", "",
         f"*Generated by `kb.py render` on {today}. Do not edit; edit `refs.jsonl` / `notes/` and re-render.*", ""]
    if meta.get("questions"):
        L += ["**Research questions**", ""] + [f"{i}. {q}" for i, q in enumerate(meta["questions"], 1)] + [""]
    L += ["| | " + " | ".join(STATUSES) + " | total |", "|---|" + "---|" * (len(STATUSES) + 1),
          "| records | " + " | ".join(str(len(by_status[s])) for s in STATUSES) + f" | {len(refs)} |", ""]
    L += ["## Rounds", "", "| round | queries | hits | new records | read |", "|---|---|---|---|---|"]
    for rn in rounds:
        ss = [s for s in searches if s["round"] == rn]
        L.append(f"| {rn} | {len(ss)} | {sum(s['hits'] for s in ss)} | {sum(s['new'] for s in ss)} | "
                 f"{sum(1 for r in read if r['round'] == rn)} |")
    L.append("")
    L += ["## Read, by trust tier", "",
          "Tier is the reader's judgement after reading (`trust-rubric.md`); `prior` is the metadata-only "
          "starting point. Quotes: ✅ every block quote found in the archived text, ❌ one is not, "
          "✋ no archived text — hand-checked only.", ""]
    for t, label in TIERS.items():
        rs = [r for r in read if r["trust"].get("tier") == t]
        if not rs:
            continue
        L += [f"### {label} ({len(rs)})", "", "| key | work | venue | year | rel | quotes | why this tier |",
              "|---|---|---|---|---|---|---|"]
        for r in sorted(rs, key=lambda r: (-(r.get("relevance") or 0), r["key"])):
            q = {True: "✅", False: "❌", None: "✋" if r.get("note") else "—"}[r.get("quotes_verified")]
            link = f"[notes](notes/{r['key']}.md)" if (kb.root / "notes" / f"{r['key']}.md").exists() else ""
            L.append(f"| `{r['key']}` {link} | {r['title']} | {r['venue'] or r['venue_type']} | {r.get('year') or ''} "
                     f"| {r.get('relevance') if r.get('relevance') is not None else ''} | {q} "
                     f"| {r['trust'].get('rationale', '').replace('|', '/')} |")
        L.append("")
    untiered = [r for r in read if not r["trust"].get("tier")]
    if untiered:
        L += ["### ⚠ read but not yet tiered", ""] + [f"- `{r['key']}`" for r in untiered] + [""]
    inc = by_status["included"]
    if inc:
        L += ["## Included, not yet read", "", "| key | work | year | prior | cited by |", "|---|---|---|---|---|"]
        for r in sorted(inc, key=lambda r: -(r.get("cited_by") or 0)):
            L.append(f"| `{r['key']}` | {r['title']} | {r.get('year') or ''} | T{r['trust'].get('prior')} | {r.get('cited_by') or ''} |")
        L.append("")
    L += ["## Search log", "", "| round | source | query | hits | new |", "|---|---|---|---|---|"]
    for s in searches:
        L.append(f"| {s['round']} | {s['source']} | {s['query'].replace('|', '/')} | {s['hits']} | {s['new']} |")
    L.append("")
    (kb.root / "INDEX.md").write_text("\n".join(L))
    bib = [r for r in refs if r["status"] in ("read", "included")]
    (kb.root / "refs.bib").write_text("\n".join(_bib(r) for r in sorted(bib, key=lambda r: r["key"])))
    print(f"rendered INDEX.md ({len(refs)} records, {len(read)} read) and refs.bib ({len(bib)} entries)")


def cmd_status(a):
    kb = KB(a.kb).require()
    refs = kb.load()
    print(f"topic: {kb.meta['topic']}")
    for s in STATUSES:
        print(f"  {s:<13} {sum(1 for r in refs if r['status'] == s)}")
    read = [r for r in refs if r["status"] == "read"]
    problems = []
    for r in read:
        if not (kb.root / "notes" / f"{r['key']}.md").exists():
            problems.append(f"{r['key']}: status=read but no note")
        if not r["trust"].get("tier"):
            problems.append(f"{r['key']}: read but no tier")
        if r.get("quotes_verified") is False:
            problems.append(f"{r['key']}: a quote does not match the archived text")
        if not r.get("verified"):
            problems.append(f"{r['key']}: identifier never resolved")
    for p in problems:
        print("  ! " + p)
    print("consistent" if not problems else f"{len(problems)} problem(s)")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sp = p.add_subparsers(dest="cmd", required=True)

    def sel(q):
        q.add_argument("keys", nargs="*")
        q.add_argument("--status")
        q.add_argument("--round", type=int)
        q.add_argument("--max-tier", type=int)
        q.add_argument("--min-relevance", type=int)

    q = sp.add_parser("init"); q.add_argument("kb"); q.add_argument("--topic", required=True)
    q.add_argument("--question", action="append"); q.add_argument("--inclusion"); q.add_argument("--exclusion")
    q.add_argument("--force", action="store_true"); q.set_defaults(f=cmd_init)

    q = sp.add_parser("search"); q.add_argument("kb"); q.add_argument("--query", required=True)
    q.add_argument("--source", choices=SOURCES, default="openalex"); q.add_argument("--round", type=int, default=1)
    q.add_argument("--limit", type=int, default=25); q.add_argument("--since", type=int)
    q.add_argument("--abstract", type=int, default=0, help="print N chars of abstract")
    q.add_argument("--fulltext", action="store_true", help="openalex: match full text too (noisier)")
    q.set_defaults(f=cmd_search)

    q = sp.add_parser("add"); q.add_argument("kb"); q.add_argument("--doi"); q.add_argument("--arxiv")
    q.add_argument("--title"); q.add_argument("--year", type=int); q.add_argument("--venue"); q.add_argument("--url")
    q.add_argument("--venue-type", choices=["journal", "conference", "preprint", "book", "thesis", "web", "unknown"])
    q.add_argument("--round", type=int, default=1); q.add_argument("--found-by"); q.set_defaults(f=cmd_add)

    q = sp.add_parser("list"); q.add_argument("kb"); sel(q)
    q.add_argument("--sort", choices=["cited", "year", "key", "relevance"], default="cited")
    q.add_argument("--abstract", type=int, default=0); q.set_defaults(f=cmd_list)

    q = sp.add_parser("show"); q.add_argument("kb"); q.add_argument("keys", nargs="+"); q.set_defaults(f=cmd_show)

    q = sp.add_parser("set", help="set KB KEY... -a field=value [-a ...]  (status, relevance, tier, rationale, factor.X, tag)")
    q.add_argument("kb"); q.add_argument("keys", nargs="+")
    q.add_argument("-a", "--assign", action="append", required=True); q.set_defaults(f=cmd_set)

    q = sp.add_parser("fetch"); q.add_argument("kb"); sel(q); q.set_defaults(f=cmd_fetch)
    q = sp.add_parser("verify-quotes"); q.add_argument("kb"); sel(q); q.set_defaults(f=cmd_verify_quotes)
    q = sp.add_parser("prior"); q.add_argument("kb"); sel(q)
    q.add_argument("--retractions", action="store_true", help="also query Crossref for retraction notices")
    q.add_argument("--no-published", action="store_true", help="skip looking up a peer-reviewed version of preprints")
    q.set_defaults(f=cmd_prior)

    q = sp.add_parser("chain"); q.add_argument("kb"); sel(q)
    q.add_argument("--direction", choices=["both", "backward", "forward"], default="both")
    q.add_argument("--to-round", type=int, required=True); q.add_argument("--min-votes", type=int, default=2)
    q.add_argument("--limit", type=int, default=40); q.set_defaults(f=cmd_chain)

    q = sp.add_parser("keypoints"); q.add_argument("kb"); sel(q); q.set_defaults(f=cmd_keypoints)
    q = sp.add_parser("render"); q.add_argument("kb"); q.set_defaults(f=cmd_render)
    q = sp.add_parser("status"); q.add_argument("kb"); q.set_defaults(f=cmd_status)

    a = p.parse_args()
    a.f(a)


if __name__ == "__main__":
    main()
