"""Generate docs/DATASET_CARD.md from the manifests and finalize summaries. Numbers are never typed.

    python -m builder.card --release /data/scmd-bench/v1 --items data/v1
"""

from __future__ import annotations

import argparse
import collections
import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _mix(items, k):
    tot = collections.Counter()
    n = 0
    for it in items:
        b = it["meta"]["bases"].get(k)
        if not b:
            continue
        n += 1
        for t, c in b["tiers"].items():
            tot[t] += c
    distr = sum(v for t, v in tot.items() if t != "gold")
    return n, {t: round(tot[t] / distr, 4) for t in ("retrieval_hard", "sibling", "random")} if distr else {}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--release", type=Path, required=True)
    ap.add_argument("--items", type=Path, required=True)
    a = ap.parse_args(argv)
    mt = json.loads((a.release / "MANIFEST.train.json").read_text())
    mc = json.loads((a.release / "MANIFEST.candidates.json").read_text())
    L = []
    w = L.append
    w("# Dataset card — scmd-bench v1.0")
    w("")
    w("_Generated by `builder/card.py` from the release manifests and the finalize summaries._")
    w("")
    w("## Provenance")
    w("")
    w("| | |")
    w("|---|---|")
    src = mt["source"]
    w(f"| corpus | LeanDLLM `{src['shard']}`, corpus_id `{src['corpus_id'][:16]}` |")
    w("| mathlib | `fabf563a7c95a166b8d7b6efca11c8b4dc9d911f` (v4.31.0, 2026-06-15) |")
    w("| Lean / REPL | `leanprover/lean4:v4.31.0` / `0cc6026` |")
    w(f"| upstream builder commit | `{src['upstream_commit']}` |")
    w(f"| hypothesis bank sha256 | `{src['hyp_bank_sha256'][:16]}…` |")
    w(f"| BM25 | k1 = {src['hard_negatives_key']['k1']}, b = {src['hard_negatives_key']['b']}, over {src['hard_negatives_key']['n_docs']:,} premises |")
    w("")
    w("The chain is as follows:")
    w("")
    w("1. mathlib source is elaborated declaration by declaration (LeanDLLM S2).")
    w("2. Each theorem's source-level dependencies are resolved against the environment (S3).")
    w("3. Premises with no source record are rendered from a Lean-verified binder-type bank (S7b).")
    w("4. corpus_v2 is built, and three splits are drawn: `file`, `temporal`, `novel_premises` (S8b).")
    w("5. This repository exports text and draws evaluation BASEs.")
    w("")
    w("## Training release")
    w("")
    w(f"- **{mt['n_train_rows']:,} rows**: {mt['row_rule']}.")
    w(f"  {mt.get('n_rows_without_location', 0):,} of them have no file location (their file's")
    w("  extraction failed). They carry the shard's own statement and proof, and can never be")
    w("  evaluation items.")
    w(f"- **{mt['n_premises']:,} premises**, of which {mt['n_drawable']:,} are drawable as distractors.")
    w("  The rest are gold-only renderings from the bank.")
    w(f"- **{mt['n_hard_lists']:,} BM25 hard-negative lists** (top 64 per target).")
    w(f"- **{mt['n_modules']:,} modules**, with public/private import edges.")
    w("- `proof` is the corpus's own proof text, and it is what SCMD trains on.")
    w("- `proof_pointers` is the same proof with `⟪dJ⟫` for dependency J.")
    w("- `proof_source` is mathlib's original text.")
    w("")
    w("## Evaluation items: filters, in order, with what each removed")
    w("")
    w("| stage | count |")
    w("|---|---|")
    for key, v in mc["filter_counts"].items():
        w(f"| {key.replace('_', ' ')} | {v:,} |")
    w("")
    for split in ("dev", "test"):
        sp = a.items / f"_finalize.{split}.summary.json"
        if not sp.is_file():
            continue
        s = json.loads(sp.read_text())
        items = [json.loads(l) for l in (a.items / f"{split}.jsonl").read_text().splitlines() if l.strip()]
        graded = s["n_candidates"] - s["reasons"].get("surplus", 0) - s["reasons"].get("not_graded", 0)
        rej = {k: v for k, v in s["reasons"].items() if k not in ("surplus", "not_graded", "witness_from_proof_source")}
        n_rej = sum(rej.values())
        w(f"### {split}: {s['n_kept']} items")
        w("")
        w(f"- **Gold-oracle filter.** Candidates were graded in a fixed order until {s['n_kept']} passed.")
        w(f"  {n_rej} were rejected, a pass rate of {s['n_kept'] / max(1, s['n_kept'] + n_rej):.3f} over")
        w("  the graded prefix. Rejections by reason:")
        w("")
        w("  | reason | n |")
        w("  |---|---|")
        for k2, v2 in sorted(rej.items(), key=lambda x: -x[1]):
            w(f"  | {k2} | {v2} |")
        w("")
        w(f"- **Witness from mathlib's own proof text.** {s['reasons'].get('witness_from_proof_source', 0)} items;")
        w("  for the rest, the corpus rendering verified.")
        amb = sum(1 for it in items if it["meta"]["ambient_solvable"])
        w(f"- **Ambient floor.** {amb} / {len(items)} = {amb / max(1, len(items)):.3f} are solved by a")
        w(f"  zero-parameter tactic. The headline subset `premise_necessary` has {len(items) - amb} items.")
        by = collections.Counter(t for it in items for t in it["meta"]["ambient_solved_by"])
        if by:
            w("  Solved by: " + ", ".join(f"`{t}` {c}" for t, c in by.most_common()) + ".")
        held = collections.Counter(h for it in items for h in it["meta"]["heldout_in"])
        w("- **Held out in.** " + ", ".join(f"`{h}` {c}" for h, c in held.most_common())
          + ". An item can be held out in more than one split.")
        ng = [it["meta"]["n_gold"] for it in items]
        w(f"- **Gold dependencies.** Mean {statistics.mean(ng):.2f}, median {statistics.median(ng)},"
          f" max {max(ng)}. {sum(1 for x in ng if x <= 16)} items have a K = 16 variant.")
        for k in ("64", "16"):
            n, mix = _mix(items, k)
            w(f"- **Realised distractor mix at K = {k}** ({n} items): " + ", ".join(f"{t} {v}" for t, v in mix.items())
              + ". The nominal endpoint is 0.65 / 0.25 / 0.10.")
        w("")
    w("## Known limitations")
    w("")
    w("- **Exposure.** Every target is in public mathlib, so web-pretrained models may have seen the")
    w("  proofs. RULES §2.3 requires this to be declared.")
    w("- **The gold label is the corpus's.** Items whose dependencies were misresolved upstream, and")
    w("  for which no witness verifies, are dropped, not repaired. This removes a population that is")
    w("  slightly skewed toward tactic-keyword and namespace-heavy proofs.")
    w("- **In-closure draw.** Distractors are drawn from each target's import closure. The realised")
    w("  mixture above is below the nominal `sibling` share, because a file supplies few siblings. The")
    w("  shortfall goes to `retrieval_hard`.")
    w("- **Reach.** Tactics can still reach lemmas outside BASE without naming them. This is reported")
    w("  per attempt; the headline subset controls the zero-parameter part of it.")
    w("- **Premise texts are SOURCE renderings** (mathlib's own signature). They can depend on file-level")
    w("  `variable`s that are not shown.")
    (ROOT / "docs/DATASET_CARD.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
